### ISSUE TITLE
How to get numbers in Table 2?

### ISSUE THREAD

**Issue by ghost** [geifmany/selectivenet#6]
Hi! Thanks for sharing the code! 

I have a hard time understanding how the results generated by your code is replicating Table 2 in the paper https://arxiv.org/pdf/1901.09192.pdf:
![image](https://user-images.githubusercontent.com/57047646/121996630-c8d53280-cd5d-11eb-9394-2784f7c771ab.png)

For example the code gives the following output with `coverage=0.95`, `baseline=none` and `dataset=cifar10`: 
```
{"0.9273": {"lambda": 0.95, "selective_risk": 0.030303030303030304}}
```

Another example with the same setting but different coverage is when `coverage=0.7`, and the output is:
```
{"0.7801": {"lambda": 0.7, "selective_risk": 0.8637354185360852}}
```
How do I relate these numbers to the numbers reported in the table? 

I appreciate your efforts :)

**Comment by aligholami** [comment]
Following the previous comment, are the numbers reported under "SelectiveNet Risk" column in Table 2, same as "Empirical Selective Risk" averaged for all batches?
